Added methods `get_payment_form and` `send_payment_form`
TelegramPlayGround/pyrogram pull request #89
Opened 2024-09-02 18:02 UTC by yehuda-lev

https://github.com/KurimuzonAkuma/pyrogram/commit/b27d0396cf0b22d59e81bfd202e32d92ab8d094a

2024-09-02 22:39 UTC, SpEcHiDe requested changes

2024-09-02 22:39 UTC, SpEcHiDe commented on pyrogram/methods/business/get_payment_from.py
> +            match = re.match(r"^(?:https?://)?(?:www\.)?(?:t(?:elegram)?\.(?:org|me|dog)/\$)([\w-]+)$", invoice_link)
Is it possible to move the regexes used to a common place, like 
https://github.com/TelegramPlayGround/pyrogram/blob/L186/pyrogram/client.py#L239 ?

2024-09-02 22:39 UTC, SpEcHiDe commented on pyrogram/methods/business/send_payment_from.py
> +            match = re.match(r"^(?:https?://)?(?:www\.)?(?:t(?:elegram)?\.(?:org|me|dog)/\$)([\w-]+)$", invoice_link)
since the same regex is used in atleast two places it would be nice if it was placed at one common place

https://github.com/TelegramPlayGround/pyrogram/blob/L186/pyrogram/client.py#L239

2024-09-02 22:57 UTC, yehuda-lev commented on pyrogram/methods/business/get_payment_from.py
> +            match = re.match(r"^(?:https?://)?(?:www\.)?(?:t(?:elegram)?\.(?:org|me|dog)/\$)([\w-]+)$", invoice_link)
Hmmm is adding it to business/init good?

2024-09-02 23:06 UTC, yehuda-lev commented
I added it to `Clinet`, I didn't find another file..

2024-09-03 02:30 UTC, SpEcHiDe approved these changes

2024-09-03 02:31 UTC, merged